[versions]
androidMinSdk = "23"
androidTargetSdk = "36"
androidCompileSdk = "36"

quickie = "1.16.0"

androidGradle = "8.13.2"
kotlin = "2.3.0"

appcompat = "1.7.1"
core = "1.17.0"

cameraX = "1.5.2"

materialDesign = "1.13.0"

detekt = "1.23.8"
dokka = "2.1.0"

junit = "6.0.2"
zxingAndroidEmbedded = "4.3.0"
desugaring = "2.1.5"

barcodeScanning = "17.3.0"
barcodeScanningGms = "18.3.1"
coil = "3.3.0"
ezVcard = "0.12.1"

[libraries]
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-camera = { module = "androidx.camera:camera-camera2", version.ref = "cameraX" }
androidx-cameraLifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraX" }
androidx-cameraPreview = { module = "androidx.camera:camera-view", version.ref = "cameraX" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
ez-vcard = { module = "com.googlecode.ez-vcard:ez-vcard", version.ref = "ezVcard" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }

google-materialDesign = { module = "com.google.android.material:material", version.ref = "materialDesign" }
mlkit-barcodeScanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
mlkit-barcodeScanningGms = { module = "com.google.android.gms:play-services-mlkit-barcode-scanning", version.ref = "barcodeScanningGms" }

test-junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
test-junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradle" }
android-library = { id = "com.android.library", version.ref = "androidGradle" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }